
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2
# Monitor
monitor = eDP-1, 1920x1080@60, 0x0, 1, bitdepth, 10

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0
    force_no_accel = 1
}

# Window rules
windowrulev2 = opacity 0.80 0.80,class:^(virt-manager)$
windowrulev2 = opacity 0.80 0.80,class:^(spotube)$
windowrulev2 = opacity 1 1,title:^(.*YouTube.*)$
windowrulev2 = opacity 1 1,title:^(.*Facebook.*)$
windowrulev2 = opacity 1 1,title:^(.*YTS.*)$
windowrulev2 = opacity 1 1,title:^(.*Solarmovie.*)$
windowrulev2 = opacity 1 1,title:^(.*animepahe.*)$

# Theme
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10
    drop_shadow = false

    blur {
        enabled = yes
        size = 5
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = unset,waybar
