
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2
# Monitor
monitor = eDP-1, 1920x1080@60, 0x0, 1, bitdepth, 10

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0
    force_no_accel = 1
}

# Window rules
windowrulev2 = opacity 0.80 0.80,class:^(virt-manager)$
windowrulev2 = opacity 0.80 0.80,class:^(spotube)$
windowrulev2 = opacity 1 1,title:^(.*YouTube.*)$
windowrulev2 = opacity 1 1,title:^(.*Facebook.*)$
windowrulev2 = opacity 1 1,title:^(.*YTS.*)$
windowrulev2 = opacity 1 1,title:^(.*Solarmovie.*)$

# Theme
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10
    drop_shadow = false

    blur {
        enabled = yes
        size = 5
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = unset,waybar

# Keybindings
bind = $mainMod, f5, exec, $scrPath/keyboardswitch.sh # switch keyboard layout

# Move/Change window focus
bind = Alt, H, movefocus, l
bind = Alt, L, movefocus, r
bind = Alt, K, movefocus, u
bind = Alt, J, movefocus, d

# Switch workspaces
bind = $mainMod, H, workspace, 1
bind = $mainMod, J, workspace, 2
bind = $mainMod, K, workspace, 3
bind = $mainMod, L, workspace, 4
bind = $mainMod, semicolon, workspace, 5
bind = $mainMod, N, workspace, 6
bind = $mainMod, M, workspace, 7
bind = $mainMod, comma, workspace, 8
bind = $mainMod, dot, workspace, 9
bind = $mainMod, slash, workspace, 10

# Move focused window to a workspace
bind = $mainMod+Ctrl, H, movetoworkspace, 1
bind = $mainMod+Ctrl, J, movetoworkspace, 2
bind = $mainMod+Ctrl, K, movetoworkspace, 3
bind = $mainMod+Ctrl, L, movetoworkspace, 4
bind = $mainMod+Ctrl, semicolon, movetoworkspace, 5
bind = $mainMod+Ctrl, N, movetoworkspace, 6
bind = $mainMod+Ctrl, M, movetoworkspace, 7
bind = $mainMod+Ctrl, comma, movetoworkspace, 8
bind = $mainMod+Ctrl, dot, movetoworkspace, 9
bind = $mainMod+Ctrl, slash, movetoworkspace, 10

# Move focused window around the current workspace
bind = $mainMod+Shift, H, movewindow, l
bind = $mainMod+Shift, L, movewindow, r
bind = $mainMod+Shift, K, movewindow, u
bind = $mainMod+Shift, J, movewindow, d

# Toggle focused window split
bind = $mainMod+Shift, S, togglesplit

# Move focused window to a workspace silently
bind = $mainMod+Alt, H, movetoworkspacesilent, 1
bind = $mainMod+Alt, J, movetoworkspacesilent, 2
bind = $mainMod+Alt, K, movetoworkspacesilent, 3
bind = $mainMod+Alt, L, movetoworkspacesilent, 4
bind = $mainMod+Alt, semicolon, movetoworkspacesilent, 5
bind = $mainMod+Alt, N, movetoworkspacesilent, 6
bind = $mainMod+Alt, M, movetoworkspacesilent, 7
bind = $mainMod+Alt, comma, movetoworkspacesilent, 8
bind = $mainMod+Alt, dot, movetoworkspacesilent, 9
bind = $mainMod+Alt, slash, movetoworkspacesilent, 10
